# Generated by Django 3.0.2 on 2020-01-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journal_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='entry_date'),
        ),
    ]
