# Generated by Django 3.0.2 on 2020-01-23 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_auto_20200120_2014'),
        ('journal', '0006_auto_20200113_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='goal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='goals.Goal'),
            preserve_default=False,
        ),
    ]
