# Generated by Django 3.0.2 on 2020-01-17 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_subgoal_goal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subgoal',
            options={'verbose_name_plural': 'Sub Goals'},
        ),
    ]
