# Generated by Django 3.0.2 on 2020-01-20 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_auto_20200116_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('due', models.DateField()),
                ('completed', models.BooleanField()),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goals.Goal')),
            ],
            options={
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.DeleteModel(
            name='SubGoal',
        ),
    ]
