# Generated by Django 2.2.9 on 2020-01-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_auto_20200120_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
