# Generated by Django 2.2.9 on 2020-01-27 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0008_auto_20200125_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(),
        ),
    ]
